version: '3'

services:
  redis:
    container_name: monorepo-redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
  jaegertracing:
    container_name: monorepo_jaegertracing
    image: jaegertracing/all-in-one:latest
    env_file:
      - .env
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
