version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount the NGINX config file
    ports:
      - '80:80'
    restart: always
  db:
    container_name: monorepo-mongo
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
  redis:
    container_name: monorepo-redis
    image: 'redis:alpine'
    restart: always
    ports:
      - 6379:6379
  jaegertracing:
    container_name: monorepo_jaegertracing
    image: jaegertracing/all-in-one:latest
    env_file:
      - .env
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
  peerjs-server:
    container_name: peerjs-server
    image: peerjs/peerjs-server
    restart: always
    ports:
      - '9000:9000'
    depends_on:
      - nginx
  api:
    container_name: voffice-api
    image: duchoang206h/voffice-be:1715188458
    restart: always
    env_file:
      - .env
    ports:
      - '2567:2567'
    depends_on:
      - nginx
      - db
      - redis
      - peerjs-server
