version: '3'
services:
  db:
    container_name: monorepo-mongo
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  redis:
    container_name: monorepo-redis
    image: 'redis:alpine'
    restart: always
    ports:
      - 6379:6379
  peerjs-server:
    container_name: peerjs-server
    image: peerjs/peerjs-server
    restart: always
    ports:
      - '9000:9000'
  api:
    container_name: voffice-api
    image: duchoang206h/voffice-be:$TAG
    restart: always
    env_file:
      - .env
    ports:
      - '2567:2567'
    depends_on:
      - db
      - redis
      - peerjs-server
volumes:
  mongo-data:
