name: Build and deploy

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: |
          export TAG=$(date +'%s')
          docker build -f Dockerfile -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
        env:
          IMAGE_NAME: ${{secrets.IMAGE_NAME}}

      - name: multiple command
        uses: appleboy/ssh-action@v1.0.0
        env:
          TAG: ${{ env.TAG }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/projects/VirtualOffice-BE
            export TAG=$TAG
            envsubst < docker-compose.template.yaml > docker-compose.yaml 
            docker compose -f docker-compose.yaml up -d
